name: Build and Deploy CSS to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install Sass
        run: npm install -g sass

      - name: Create dist folder
        run: mkdir -p dist

      - name: Compile SCSS to CSS
        run: sass src/color-utilities.scss dist/color-utilities.css

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
